### ISSUE TITLE
short php tags make this library not work with php7

### ISSUE THREAD

**Issue by danielzzz** [ardabeyazoglu/php-push#1]
hi, it seems that the short opening tags you're using (<?) are not compatible with php 7.2 (at least in my config)

changing everything to <?php solves the problem.

cheers, dan

**Comment by ardabeyazoglu** [comment]
Hi, thanks for the info. That's right, the standard way is using <?php for that. 
Would you like to replace them and send me a pull request ?

**Comment by danielzzz** [comment]
done, sorry for mutiple commits - did it directly from the github web interface

https://github.com/ardabeyazoglu/php-push-helper/pull/2

**Comment by ardabeyazoglu** [comment]
No problem, thanks.
